/home/vs/Projects/welsib-independent/welsib-smpc/example/smpc-client-part1-example-point.pem
/home/vs/Projects/welsib-independent/welsib-smpc/example/smpc-client-part2-example-point.pem
/home/vs/Projects/welsib-independent/welsib-smpc/example/smpc-client-sum-example-point.pem
/home/vs/Projects/welsib-independent/welsib-smpc/example/smpc-server-example-point.pem
