/home/vs/Projects/welsib-independent/welsib-smpc/example_constructor/keys/public/smpc-client-value47-point.pem
/home/vs/Projects/welsib-independent/welsib-smpc/example_constructor/keys/public/smpc-client-value18-point.pem
/home/vs/Projects/welsib-independent/welsib-smpc/example_constructor/keys/public/smpc-client-value35-point.pem
/home/vs/Projects/welsib-independent/welsib-smpc/example_constructor/keys/public/smpc-client-value100-point.pem
/home/vs/Projects/welsib-independent/welsib-smpc/example_constructor/keys/public/smpc-server-point.pem
